### ISSUE TITLE
Htmx style frontend

### ISSUE THREAD

**Issue by gedw99** [iammuho/NatterNet#27]
Easy to update parts of any html / go template based gui 

and also easy to extend in a decoupled way with plugins for other gui elements etc .

I have been using htmx for gui where you want to update parts in real time . Htmx can use WS or SSE to update the gui html is response to bsckend events

**Comment by gedw99** [comment]
https://github.com/stackus/todos Is a hood example

**Comment by gedw99** [comment]
You can compile to wasm and so have the htmx happen on the client 

https://github.com/stackus/todos-htmx-wasm

**Comment by iammuho** [comment]
Hey @gedw99 ,

You suggest that for the client example right? Because this project offers only API server but I also agree to do some example client.

Can you contribute to that ?

**Comment by gedw99** [comment]
I cant sorry . No time currently.

the todo examples are there.

**Comment by iammuho** [comment]
https://github.com/iammuho/NatterNet/issues/12
